"""`make contracts` goes red on a stale artefact.

"It is not enough that the definition exists — it must be provable that everyone is using
it, now." The proof is mechanical: recompile every consumer in memory and refuse the build
if what is on disk differs. That catches both directions of drift — a contract edited
without regenerating, and a generated file edited by hand — and it is the reason a
hand-edited consumer cannot quietly become a second definition.

`check` never writes. A build step that repairs the thing it is checking cannot fail.
"""

from __future__ import annotations

import re
import shutil
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

from holdout.contracts.cli import main
from holdout.contracts.compilers import compile_all
from holdout.contracts.compilers.readout import compile_readout
from holdout.contracts.errors import CompilationError
from holdout.contracts.loader import CONTRACTS_DIR, REPO_ROOT, load


@pytest.fixture
def sandbox(tmp_path: Path) -> Path:
    """A copy of the repository's contracts and generated tree, so a test may vandalise it."""
    shutil.copytree(CONTRACTS_DIR, tmp_path / "contracts")
    shutil.copytree(REPO_ROOT / "generated", tmp_path / "generated")
    return tmp_path


def run(sandbox: Path, command: str = "check") -> int:
    return main([command, "--contracts", str(sandbox / "contracts"), "--root", str(sandbox)])


def test_the_committed_artefacts_match_their_contracts() -> None:
    """The one that fails on a real branch when someone forgets `make contracts-write`."""
    assert main(["check"]) == 0


def test_generation_does_not_depend_on_where_the_repository_sits(sandbox: Path) -> None:
    """An untouched copy of the contracts, checked out somewhere else, must still be green.

    It was not. A generated artefact names its source contract in its header, and that name
    used to be resolved against a fixed repository root, so a copy anywhere else compiled to
    different bytes and read as stale. Every negative test in this file that only asserted a
    non-zero exit code was therefore passing for the wrong reason — the sandbox was already
    red before the test vandalised anything. This is the test that would have said so.
    """
    assert run(sandbox) == 0


def test_a_hand_edited_artefact_makes_the_build_red(
    sandbox: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    target = sandbox / "generated" / "dbt" / "models" / "metrics"
    model = next(target.glob("*.sql"))
    model.write_text(
        model.read_text(encoding="utf-8").replace("bround(", "round("), encoding="utf-8"
    )
    assert run(sandbox) == 1
    assert "stale_artefact" in capsys.readouterr().err


def test_a_one_character_edit_is_enough(sandbox: Path) -> None:
    """Compared byte for byte, because the interesting drift is small.

    Half-even to half-up is four characters and one cent, and one cent is a failed claim 5.
    """
    model = next((sandbox / "generated" / "readout").glob("*.sql"))
    model.write_text(model.read_text(encoding="utf-8") + " ", encoding="utf-8")
    assert run(sandbox) == 1


def test_a_deleted_artefact_makes_the_build_red(
    sandbox: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    next((sandbox / "generated" / "agent_tools").glob("*.json")).unlink()
    assert run(sandbox) == 1
    assert "missing_artefact" in capsys.readouterr().err


def test_a_file_under_generated_that_no_contract_compiles_to_makes_the_build_red(
    sandbox: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A hand-written file under generated/ will be read as generated by everyone after."""
    (sandbox / "generated" / "readout" / "quick_fix.sql").write_text("select 1\n", "utf-8")
    assert run(sandbox) == 1
    assert "orphan_artefact" in capsys.readouterr().err


def test_check_does_not_repair_what_it_is_checking(sandbox: Path) -> None:
    model = next((sandbox / "generated" / "sql" / "functions").glob("*.sql"))
    vandalised = model.read_text(encoding="utf-8") + "-- edited\n"
    model.write_text(vandalised, encoding="utf-8")
    assert run(sandbox) == 1
    assert model.read_text(encoding="utf-8") == vandalised
    assert run(sandbox) == 1


def test_compile_restores_what_check_refused(sandbox: Path) -> None:
    model = next((sandbox / "generated" / "sql" / "functions").glob("*.sql"))
    model.write_text("-- edited\n", encoding="utf-8")
    assert run(sandbox) == 1
    assert run(sandbox, "compile") == 0
    assert run(sandbox) == 0


def test_a_changed_contract_makes_every_artefact_it_feeds_go_red(sandbox: Path) -> None:
    """The other direction of drift: the contract moved and the consumers did not."""
    metric = sandbox / "contracts" / "metrics" / "category_margin_per_store_week.v3.yaml"
    metric.write_text(
        metric.read_text(encoding="utf-8").replace("mode: half_even", "mode: half_up"),
        encoding="utf-8",
    )
    assert run(sandbox) == 1


def test_every_generated_artefact_says_it_is_generated_and_names_its_source() -> None:
    contracts = load()
    for rel, content in compile_all(contracts).items():
        assert "GENERATED FILE — DO NOT EDIT" in content, rel
        assert "contracts/" in content, rel
        assert "make contracts" in content, rel
        assert "holdout.contracts.compilers." in content, rel


def test_generation_does_not_depend_on_the_clock() -> None:
    """An artefact that went stale at midnight on an effective date would make the staleness
    check report the calendar instead of a drift."""
    first = compile_all(load())
    second = compile_all(load())
    assert first == second
    for content in first.values():
        assert "2026-08-27" not in content


# ------------------------------------------------------ a compiler refuses rather than guesses


def test_the_readout_refuses_a_metric_whose_grain_it_cannot_window(
    contracts_copy: Path, edit_contract: Callable[[Path, Callable[[Any], Any]], None]
) -> None:
    """The readout template names two columns by hand — it joins the assignment on
    `store_id` and windows the period on `iso_week`. A metric at grain `[store_id, day]`
    would have compiled anyway and emitted a query referencing a column no CTE selects: still
    valid text, still matching the staleness check, still wrong, and wrong only at the moment
    someone reads a result off it. A compiler may be opinionated; it may not guess.
    """

    def regrain(document: Any) -> Any:
        document["grain"] = ["store_id", "day", "category"]
        return document

    edit_contract(contracts_copy / "metrics" / "units_sold_per_store_week.v1.yaml", regrain)
    contracts = load(contracts_copy)
    metric = contracts.metric_versions("units_sold_per_store_week")[0]
    with pytest.raises(CompilationError, match="iso_week"):
        compile_readout(metric)


def test_a_metric_the_readout_cannot_compile_makes_the_build_red(
    sandbox: Path,
    edit_contract: Callable[[Path, Callable[[Any], Any]], None],
    capsys: pytest.CaptureFixture[str],
) -> None:
    def regrain(document: Any) -> Any:
        document["grain"] = ["region_id", "iso_week"]
        return document

    edit_contract(sandbox / "contracts" / "metrics" / "waste_value_per_store_week.v1.yaml", regrain)
    assert run(sandbox) == 1
    assert "not_compilable" in capsys.readouterr().err


# ------------------------------------------------------------- the number that must be able to hurt


def test_the_provenance_ratio_is_reported_on_a_red_build_too(
    sandbox: Path,
    edit_contract: Callable[[Path, Callable[[Any], Any]], None],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """The earlier version of this line divided a count by itself.

    It counted sources and printed `43/43 sourced`, which could not fall below 100% because a
    value with no source raises before the line is reached. The denominator is now every
    `value` the walk found, and the census is carried on the failure, so a build with an
    unsourced value prints a ratio short of its denominator above the violation list.
    """
    before = run(sandbox)
    assert before == 0
    sourced, total = _ratio(capsys.readouterr().out)
    assert sourced == total and sourced > 0

    def unsource(document: Any) -> Any:
        document["windows"][0]["rules"][0]["thresholds"] = {"value": 3}
        return document

    edit_contract(sandbox / "contracts" / "guardrails" / "floor.yaml", unsource)
    assert run(sandbox) == 1
    red = capsys.readouterr().err
    assert _ratio(red) == (sourced, total + 1), red.splitlines()[:2]


def _ratio(output: str) -> tuple[int, int]:
    """The provenance line's two numbers, read out of the build's own output.

    Read rather than written down. The figures were literals here — `59/59` and `59/60` — and
    a literal in a test about a *ratio* has to be edited every time a contract grows a number,
    which is a test that goes red for the one reason it is not about. What the line has to do
    is fall short of its denominator when a value loses its source, and that is a relation
    between the two numbers rather than either of them.
    """
    found = re.search(r"(\d+)/(\d+) values carry a source", output)
    assert found is not None, f"no provenance line in:\n{output}"
    return int(found.group(1)), int(found.group(2))


def test_the_ratio_counts_values_and_not_sources() -> None:
    """The two differ: a policy step carries a source and no `value` key at all."""
    contracts = load()
    assert contracts.census.legal + contracts.census.scenario > contracts.census.values
