"""Training, evaluation and promotion — the code, proved local.

`CLAUDE.md` splits this in two and only the first half is here: *"the training **logic** — the
time split, the censoring correction, the calibration gate, the promotion gates — is pure code
and is proved local against a small corpus. The run that produces the model actually used is
executed on the estate, during `backfill`."* So nothing in this package trains the model anyone
ships. What it does is make every rule that model will be judged by executable, refusable and
planted against, before a workspace exists.

What this package forecasts, and the measurement that decided it
----------------------------------------------------------------
**Units at the price the policy will set. Not units at a candidate price.**

`CLAUDE.md` asks for the second — *"forecasting demand at each candidate price and time"* is the
first row of the model's side of the boundary table, and `core.pricing.Scenario` takes
`expected_units` per candidate price as data. **It is not identified on this corpus, and that is
measured rather than argued.** Over `PriceDecision` events at `rehearsal`:

    W1 (A/A)   discount levels per hours-to-expiry bucket:  {3:1, 6:1, 12:1, 16:1}
    W6         discount levels per hours-to-expiry bucket:  {3:2, 6:2, 12:2, 16:2}
    both       discount levels per (hours, arm):            exactly 1

`corpus/world/policy.py`'s `price_cents(base, hours)` is a step function with no noise and no
exploration, so **price is a deterministic function of hours-to-expiry within an arm.** On
ordinary history there is no price contrast at all; in a world with an experiment running there
is exactly one, and it is the treatment/control contrast the experiment exists to measure. A
model fitted through it would learn its price response from the readout's own answer and the
readout would then be scoring a model trained on it.

`CLAUDE.md` predicts this exactly and names the remedy — *"deliberate price randomisation on a
small share of decisions, because the history was generated by our own policy and contains almost
no evidence about prices we never chose"* — and **that randomisation is not built**. This package
is the first consumer that needed it. The finding is in `docs/FINDINGS.md`, paired with the other
property this corpus cannot express, because both would change every world and cost the same
expensive rebuild.

**So the hole is left open rather than filled with a declared elasticity.** A number in
`contracts/ml/training.yaml` saying how demand responds to price would be inventing the one thing
the model exists to learn — doctrine rule 3, in the file that exists to refuse it.

What is here
------------
=================  ===========================================================
`split`            the time-based split, and the leaks it refuses
`features`         gold's demand features, with claim 4's correction applied
`model`            the demand model: segment rates, shrunk, exactly reproducible
`calibration`      what the evaluation half says about a fitted model
`promotion`        the gates, and the named human who is then allowed to decide
=================  ===========================================================

Two things this package is not
------------------------------
**It is not in the closed refusal vocabulary, and that is a decision rather than an omission.**
`contracts/vocabularies/reason_codes.yaml` says *"three moments, because the system refuses three
different things"* — a price, an experiment, a number — and `guardrails.Refusal` says where such a
refusal goes: *"to the decision record, to the decision monitor's refusal table, and — at the same
size as an uplift — to the experiment readout."* **A promotion refusal goes to none of those
three.** Nobody asked this pipeline for a price, a design or a number; claim 1 counts decision
refusals and claim 6 counts design refusals, and no claim counts a refused model. It refuses the
way `make check` refuses: a named, enumerable check with a stable id, proved by planting. If a
claim ever asks *how often does this system decline to act* across both populations, a fourth
section becomes right — and that is a contract change with a restatement chain, named here so the
next reader finds a criterion rather than an oversight.

**And it is not MLflow.** The registry, the endpoint and the run that produces the deployed model
are phase 3. A model here is a plain frozen object with a digest over the numbers that define it,
so two fits of the same data are the same model or they are a bug.

No library was needed, and that is worth saying
-----------------------------------------------
Nothing here imports numpy, scipy or scikit-learn, because the repository has none of them and the
model does not need one: it is counts, sums and exact `Fraction` shares, which is the arithmetic
`holdout.core.demand` already uses. Saying so explicitly rather than leaving it silent, because a
reader arriving at a directory called `ml/` will assume otherwise, and *no dependency was needed*
is a stronger sentence than an absence.
"""
