# **The data key, which is not the state key.**
#
# `infra/bootstrap` owns a KMS key for Terraform state, and it is on `CLAUDE.md`'s survivor list:
# it outlives every teardown, because state encrypted with a deleted key is state nobody can
# read. **This key is the opposite.** It encrypts the estate's data at rest, the estate is built
# and destroyed on purpose several times, and a key that survived would accumulate one orphaned
# key per cycle — each with a 30-day deletion window nobody is watching.
#
# So this one is created and destroyed with the layer, and the argument for the two keys being
# different objects is exactly that they have different lifetimes. That is the first of the four
# tests `CLAUDE.md` sets for a layer earning its place, applied one level down to a resource.
resource "aws_kms_key" "data" {
  description = "holdout — estate data at rest (bronze, silver, gold, landing)"

  # Annual automatic rotation. It will almost never fire on a key this short-lived, and it is
  # here because the alternative is a key whose rotation posture depends on how long somebody
  # happened to leave the estate up.
  enable_key_rotation = true

  # **Seven days rather than thirty.** The state key takes the maximum because losing it is
  # unrecoverable; this one takes the minimum AWS allows, because a cycle that is rebuilt weekly
  # would otherwise leave six weeks of pending-deletion keys in the account at once. Nothing in
  # this project ever needs to undo a data-key deletion: the data is regenerated by `backfill`.
  deletion_window_in_days = 7
}

resource "aws_kms_alias" "data" {
  name          = "alias/holdout-estate-data"
  target_key_id = aws_kms_key.data.key_id
}

# The key policy, written rather than left to the default.
#
# **The default key policy grants the account root full control and nothing else**, which is
# workable and says nothing about who is expected to use the key. This one names the two
# principals that must: the account, so a human with console access can administer it, and the
# deploy role, which is the identity every apply above this layer runs as.
data "aws_iam_policy_document" "data_key" {
  statement {
    sid       = "AccountAdministersTheKey"
    effect    = "Allow"
    actions   = ["kms:*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = ["arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
  }

  statement {
    sid    = "TheDeployRoleUsesTheKey"
    effect = "Allow"
    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey",
    ]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = [data.aws_ssm_parameter.deploy_role_arn.value]
    }
  }
}

resource "aws_kms_key_policy" "data" {
  key_id = aws_kms_key.data.id
  policy = data.aws_iam_policy_document.data_key.json
}
