# **The workspace, on a Databricks-managed network.**
#
# `CLAUDE.md`'s `foundation` row carried a VPC until 2026-09-06 and the restatement beside it is
# why there is no `network.tf`: `network_id` is optional on this resource — measured against the
# provider schema — and a customer-managed VPC hosts classic compute, which this estate never
# launches. What is *not* optional in practice is the pair below: an AWS workspace still needs a
# cross-account role Databricks can assume, and a root bucket for its own system data.

# ---------------------------------------------------------------- the workspace's root bucket
#
# **This is not one of the four zones and must not be confused with them.** The zones hold the
# lakehouse — landing, bronze, silver, gold — and are governed by Unity Catalog. This bucket is
# the workspace's own root: notebook revisions, job output, the legacy DBFS namespace. No table
# lives here and `lakehouse` grants nothing on it.
resource "aws_s3_bucket" "root" {
  bucket = "holdout-workspace-root-${local.account_suffix}"

  # Same argument as the zones: not on `CLAUDE.md`'s survivor list, and a `destroy` that stops on
  # a non-empty bucket leaves the estate half-standing.
  force_destroy = true
}

resource "aws_s3_bucket_public_access_block" "root" {
  bucket                  = aws_s3_bucket.root.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# **SSE-S3 here where the zones get KMS, and the difference is deliberate rather than an
# oversight.**
#
# A workspace root bucket encrypted with a customer-managed key needs
# `databricks_mws_customer_managed_keys` and a key policy naming Databricks' own account as a
# principal — a second cross-account trust, for the bucket that holds the least sensitive thing
# in the estate. The lakehouse data is in the four zones and those are KMS-encrypted with a key
# this account owns. **The asymmetry is the point: the control goes where the data is.**
resource "aws_s3_bucket_server_side_encryption_configuration" "root" {
  bucket = aws_s3_bucket.root.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# The bucket policy Databricks requires, **generated rather than written**.
#
# Doctrine rule 3 — *a contract compiles; it is never interpreted by hand-written code in two
# places* — applies to a vendor's required policy as much as to one of ours. Hand-copying this
# from documentation is the same act as hand-copying a metric definition: it is correct on the
# day it is copied and silently wrong the day the vendor changes it.
data "databricks_aws_bucket_policy" "root" {
  provider = databricks.account
  bucket   = aws_s3_bucket.root.bucket
}

resource "aws_s3_bucket_policy" "root" {
  bucket     = aws_s3_bucket.root.id
  policy     = data.databricks_aws_bucket_policy.root.json
  depends_on = [aws_s3_bucket_public_access_block.root]
}

resource "databricks_mws_storage_configurations" "this" {
  provider                   = databricks.account
  account_id                 = var.databricks_account_id
  bucket_name                = aws_s3_bucket.root.bucket
  storage_configuration_name = "holdout-root"
}

# ---------------------------------------------------------------- the cross-account role
#
# **The one place this account grants a third party the right to act inside it**, so both halves
# are generated by the provider rather than transcribed: the trust policy, which names
# Databricks' AWS account and requires `sts:ExternalId` to equal our Databricks account id, and
# the permission policy, which is what Databricks may then do.
#
# The external id is what stops the confused-deputy problem: without it, a trust policy naming
# Databricks' account would be satisfied by *any* Databricks customer's workspace.
data "databricks_aws_assume_role_policy" "this" {
  provider    = databricks.account
  external_id = var.databricks_account_id
}

data "databricks_aws_crossaccount_policy" "this" {
  provider = databricks.account
}

resource "aws_iam_role" "cross_account" {
  name               = "holdout-databricks-crossaccount"
  assume_role_policy = data.databricks_aws_assume_role_policy.this.json
}

resource "aws_iam_role_policy" "cross_account" {
  name   = "holdout-databricks-crossaccount"
  role   = aws_iam_role.cross_account.id
  policy = data.databricks_aws_crossaccount_policy.this.json
}

# **IAM is eventually consistent, and `depends_on` does not wait for it.**
#
# The first apply failed here with *"cannot create mws credentials: Failed credential validation
# checks: please use a valid cross account IAM role with permissions setup correctly"* — a message
# that reads like a wrong ARN or a wrong policy and is neither. Databricks validates the role by
# **assuming it** at registration time, and a role created milliseconds earlier is frequently not
# yet assumable anywhere but the region that created it.
#
# `depends_on` orders the calls; it does not make IAM's replicas agree. **This is the only
# instrument that does**, and it is the shape the Databricks provider's own documentation uses for
# this resource. Thirty seconds against a propagation that is usually under ten: the cost of being
# generous is half a minute per apply, and the cost of being tight is a failed dispatch that looks
# like a configuration error.
resource "time_sleep" "iam_propagation" {
  depends_on      = [aws_iam_role_policy.cross_account]
  create_duration = "30s"
}

resource "databricks_mws_credentials" "this" {
  provider         = databricks.account
  account_id       = var.databricks_account_id
  role_arn         = aws_iam_role.cross_account.arn
  credentials_name = "holdout-crossaccount"

  # The dependency is on the wait rather than on the policy, and the wait depends on the policy —
  # because a role with no permission policy attached fails the same validation for a different
  # reason, and that ordering still has to hold.
  depends_on = [time_sleep.iam_propagation]
}

# ---------------------------------------------------------------- the workspace
resource "databricks_mws_workspaces" "this" {
  provider       = databricks.account
  account_id     = var.databricks_account_id
  workspace_name = "holdout"
  aws_region     = var.region

  credentials_id           = databricks_mws_credentials.this.credentials_id
  storage_configuration_id = databricks_mws_storage_configurations.this.storage_configuration_id

  # **`network_id` is deliberately absent.** See the header of this file and `CLAUDE.md`'s
  # restated `foundation` row. Omitting it is what selects the Databricks-managed network, which
  # is a supported configuration rather than a default nobody chose.
}
