locals {
  # The same suffix rule `infra/bootstrap/state.tf` uses, and for the same reason: a bucket name
  # is globally unique, so it needs something account-specific, and the account id itself may not
  # appear in a public repository. A hash of it is stable, collision-free in practice, and
  # computed at apply time rather than committed.
  account_suffix = substr(sha256(data.aws_caller_identity.current.account_id), 0, 12)

  # **Four zones, and `landing` is not decoration.** `CLAUDE.md`'s ingestion table names two
  # sources that arrive as *files on S3* rather than through Zerobus — the ERP's master data,
  # dropped several times during a run, and the eight months of transaction history that
  # `backfill` bulk-loads. Those files need somewhere to be dropped, and it is not bronze:
  # bronze is *one table per source in the source's shape*, which is what the load produces, not
  # what it reads.
  #
  # The other three are the medallion layers, one bucket each rather than one bucket with three
  # prefixes. A prefix shares a bucket policy, a lifecycle configuration and a blast radius with
  # its neighbours; a bucket does not, and `lakehouse` grants Unity Catalog external locations
  # per bucket, so a mistake in a grant is scoped to one zone.
  zones = ["landing", "bronze", "silver", "gold"]
}

resource "aws_s3_bucket" "zone" {
  for_each = toset(local.zones)

  bucket = "holdout-${each.key}-${local.account_suffix}"

  # **`force_destroy = true`, and this is the argument rather than a shrug.**
  #
  # These buckets are *not* on `CLAUDE.md`'s survivor list — *what survives a teardown: the state
  # bucket and its access-log bucket, the state KMS key, the SSM parameters and the deploy role.
  # Nothing else.* A `destroy` that stops on a non-empty bucket leaves the estate half-standing,
  # which is the exact failure the budget posture refuses to cause on purpose and would then be
  # causing by accident.
  #
  # **And the TTL reaper is level 1 of three**, depending on no workflow's control flow. A reaper
  # that cannot empty a bucket is a reaper that reports success on an estate it did not collect.
  # The data here is regenerated by `backfill` from files and a seed; there is nothing in these
  # four buckets that a rerun cannot produce again.
  force_destroy = true
}

resource "aws_s3_bucket_public_access_block" "zone" {
  for_each = aws_s3_bucket.zone

  bucket                  = each.value.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "zone" {
  for_each = aws_s3_bucket.zone

  bucket = each.value.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "zone" {
  for_each = aws_s3_bucket.zone

  bucket = each.value.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.data.arn
    }
    # **Bucket keys, because the alternative is one KMS request per object.** These zones hold
    # Parquet written by Spark, which is many small files, and per-object KMS calls are both a
    # cost line and a throttling ceiling. This is the setting that makes KMS encryption on a
    # lakehouse a rounding error instead of a bill.
    bucket_key_enabled = true
  }
}

# **TLS-only, as a bucket policy rather than as a hope.**
#
# `infra/bootstrap` carries the same statement on the state bucket, and it is the one control
# here that a caller cannot opt out of: `aws:SecureTransport` is false only for a request that
# actually arrived over HTTP, so denying it costs nothing and closes a door that no other setting
# closes.
data "aws_iam_policy_document" "zone_tls_only" {
  for_each = aws_s3_bucket.zone

  statement {
    sid       = "DenyPlaintextTransport"
    effect    = "Deny"
    actions   = ["s3:*"]
    resources = [each.value.arn, "${each.value.arn}/*"]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "zone" {
  for_each = aws_s3_bucket.zone

  bucket = each.value.id
  policy = data.aws_iam_policy_document.zone_tls_only[each.key].json

  # The public access block must exist first: a bucket policy naming `Principal: *` is refused
  # while `block_public_policy` is being evaluated against a bucket that does not yet have it.
  depends_on = [aws_s3_bucket_public_access_block.zone]
}
